[nxs-sip-egress]
exten => _X.,1,GotoIf($[${LEN(${NXS_SIP_EGRESS_PERMIT})} < 100]?deny)
 same => n,GotoIf($[${LEN(${NXS_SIP_EGRESS_PERMIT})} > 2048]?deny)
 same => n,Dial(PJSIP/${EXTEN}@nxs-edge,30,b(nxs-permit-header^s^1))
 same => n,Hangup()
 same => n(deny),Hangup(21)

[nxs-permit-header]
exten => s,1,Set(PJSIP_HEADER(remove,X-NXS-Egress-Permit)=)
 same => n,Set(PJSIP_HEADER(add,X-NXS-Egress-Permit)=${NXS_SIP_EGRESS_PERMIT})
 same => n,Return()
