"""Import every ORM model so ``Base.metadata`` is complete.

Alembic autogeneration and the tenant schema guard both rely on this module having
imported all domain models. Add one import per new model module.
"""

from __future__ import annotations

from nexus_ai.domain.agents.models import (
    AiAgentRecord,
    AiAgentSessionRecord,
    AiAgentToolCallRecord,
    AiAgentTurnRecord,
    AiModelProfileRecord,
    AiModelProviderAccountRecord,
    AiModelSecretRecord,
    AiModelUsageRecord,
)
from nexus_ai.domain.auth.models import (
    MembershipRecord,
    PermissionRecord,
    RefreshSessionRecord,
    RoleAssignmentRecord,
    RolePermissionRecord,
    RoleRecord,
    UserCredentialRecord,
    UserRecord,
)
from nexus_ai.domain.campaigns.models import (
    CampaignAudienceSnapshotRecord,
    CampaignContactPreferenceRecord,
    CampaignPolicyEpochRecord,
    CampaignRecipientAttemptRecord,
    CampaignRecipientRecord,
    CampaignRecord,
    CampaignRevisionRecord,
    CampaignRunRecord,
    CampaignSendPermitRecord,
    CampaignSuppressionRecord,
    CampaignThrottleWindowRecord,
    CampaignTransitionHistoryRecord,
)
from nexus_ai.domain.cells.models import (
    CellControlHistoryRecord,
    CellRecord,
    OrganizationPlacementRecord,
    PlacementMutationRecord,
)
from nexus_ai.domain.customers.models import (
    ConversationActivityRecord,
    ConversationParticipantRecord,
    ConversationRecord,
    CustomerIdentityRecord,
    CustomerRecord,
)
from nexus_ai.domain.events.models import (
    ConsumerReceiptRecord,
    EventDeadLetterRecord,
    EventOutboxRecord,
)
from nexus_ai.domain.humans.models import (
    ConversationOwnershipRecord,
    HumanActionAuthorizationRecord,
    HumanAgentPresenceRecord,
    HumanAssignmentRecord,
    HumanHandoffRecord,
    HumanQueueRecord,
    HumanTransitionHistoryRecord,
    HumanWorkItemRecord,
)
from nexus_ai.domain.integrations.models import (
    IntegrationExecutionRecord,
    IntegrationIdempotencyRecord,
    IntegrationOperationRecord,
    IntegrationRecord,
    IntegrationSecretRecord,
    WebhookEndpointRecord,
    WebhookReceiptRecord,
)
from nexus_ai.domain.messaging.models import (
    MessagingAccountRecord,
    MessagingInboundReceiptRecord,
    MessagingMessageRecord,
    MessagingSecretRecord,
    MessagingSendIdempotencyRecord,
)
from nexus_ai.domain.organizations.models import OrganizationRecord
from nexus_ai.domain.otp.models import OtpChallengeRecord
from nexus_ai.domain.provisioning.models import (
    DashboardConfigurationRecord,
    OrganizationSettingsRecord,
    PlatformGrantRecord,
    ProvisioningRequestRecord,
)
from nexus_ai.domain.scheduler.models import (
    SchedulerOccurrenceRecord,
    SchedulerScheduleRecord,
    SchedulerTransitionHistoryRecord,
)
from nexus_ai.domain.sip_edge.models import (
    CellSipTargetHeadRecord,
    CellSipTargetRecord,
    SipAccountUpstreamHistoryRecord,
    SipAccountUpstreamRecord,
    SipDialogBindingRecord,
    SipDidLocatorRecord,
    SipEdgeAuthHeadRecord,
    SipEdgeReplayRecord,
    SipEgressDialogBindingRecord,
    SipEgressHistoryRecord,
    SipEgressPermitRecord,
    SipEgressRouteRecord,
    SipPeerHistoryRecord,
    SipPeerProfileRecord,
    SipRouteAuthorizationRecord,
    SipRouteHistoryRecord,
    SipTargetMutationRecord,
    SipTargetRouteReferenceRecord,
    SipUpstreamRecord,
)
from nexus_ai.domain.telephony.models import (
    TelephonyAccountRecord,
    TelephonyCallEventRecord,
    TelephonyCallRecord,
    TelephonyMediaSessionRecord,
    TelephonyPhoneNumberRecord,
    TelephonySecretRecord,
)
from nexus_ai.domain.tools.models import (
    ToolDefinitionRecord,
    ToolExecutionRecord,
    ToolIdempotencyRecord,
)
from nexus_ai.domain.voice.models import (
    VoiceProfileRecord,
    VoiceProviderAccountRecord,
    VoiceProviderEventRecord,
    VoiceSecretRecord,
    VoiceSessionRecord,
    VoiceUsageRecordRecord,
)
from nexus_ai.domain.workflows.models import (
    WorkflowDefinitionRecord,
    WorkflowRunRecord,
    WorkflowStepRunRecord,
    WorkflowTransitionHistoryRecord,
    WorkflowVersionRecord,
    WorkflowVersionStepRecord,
)

__all__ = [
    "AiAgentRecord",
    "AiAgentSessionRecord",
    "AiAgentToolCallRecord",
    "AiAgentTurnRecord",
    "AiModelProfileRecord",
    "AiModelProviderAccountRecord",
    "AiModelSecretRecord",
    "AiModelUsageRecord",
    "CampaignAudienceSnapshotRecord",
    "CampaignContactPreferenceRecord",
    "CampaignPolicyEpochRecord",
    "CampaignRecipientAttemptRecord",
    "CampaignRecipientRecord",
    "CampaignRecord",
    "CampaignRevisionRecord",
    "CampaignRunRecord",
    "CampaignSendPermitRecord",
    "CampaignSuppressionRecord",
    "CampaignThrottleWindowRecord",
    "CampaignTransitionHistoryRecord",
    "CellControlHistoryRecord",
    "CellRecord",
    "CellSipTargetHeadRecord",
    "CellSipTargetRecord",
    "ConsumerReceiptRecord",
    "ConversationActivityRecord",
    "ConversationOwnershipRecord",
    "ConversationParticipantRecord",
    "ConversationRecord",
    "CustomerIdentityRecord",
    "CustomerRecord",
    "DashboardConfigurationRecord",
    "EventDeadLetterRecord",
    "EventOutboxRecord",
    "HumanActionAuthorizationRecord",
    "HumanAgentPresenceRecord",
    "HumanAssignmentRecord",
    "HumanHandoffRecord",
    "HumanQueueRecord",
    "HumanTransitionHistoryRecord",
    "HumanWorkItemRecord",
    "IntegrationExecutionRecord",
    "IntegrationIdempotencyRecord",
    "IntegrationOperationRecord",
    "IntegrationRecord",
    "IntegrationSecretRecord",
    "MembershipRecord",
    "MessagingAccountRecord",
    "MessagingInboundReceiptRecord",
    "MessagingMessageRecord",
    "MessagingSecretRecord",
    "MessagingSendIdempotencyRecord",
    "OrganizationPlacementRecord",
    "OrganizationRecord",
    "OrganizationSettingsRecord",
    "OtpChallengeRecord",
    "PermissionRecord",
    "PlacementMutationRecord",
    "PlatformGrantRecord",
    "ProvisioningRequestRecord",
    "RefreshSessionRecord",
    "RoleAssignmentRecord",
    "RolePermissionRecord",
    "RoleRecord",
    "SchedulerOccurrenceRecord",
    "SchedulerScheduleRecord",
    "SchedulerTransitionHistoryRecord",
    "SipAccountUpstreamHistoryRecord",
    "SipAccountUpstreamRecord",
    "SipDialogBindingRecord",
    "SipDidLocatorRecord",
    "SipEdgeAuthHeadRecord",
    "SipEdgeReplayRecord",
    "SipEgressDialogBindingRecord",
    "SipEgressHistoryRecord",
    "SipEgressPermitRecord",
    "SipEgressRouteRecord",
    "SipPeerHistoryRecord",
    "SipPeerProfileRecord",
    "SipRouteAuthorizationRecord",
    "SipRouteHistoryRecord",
    "SipTargetMutationRecord",
    "SipTargetRouteReferenceRecord",
    "SipUpstreamRecord",
    "TelephonyAccountRecord",
    "TelephonyCallEventRecord",
    "TelephonyCallRecord",
    "TelephonyMediaSessionRecord",
    "TelephonyPhoneNumberRecord",
    "TelephonySecretRecord",
    "ToolDefinitionRecord",
    "ToolExecutionRecord",
    "ToolIdempotencyRecord",
    "UserCredentialRecord",
    "UserRecord",
    "VoiceProfileRecord",
    "VoiceProviderAccountRecord",
    "VoiceProviderEventRecord",
    "VoiceSecretRecord",
    "VoiceSessionRecord",
    "VoiceUsageRecordRecord",
    "WebhookEndpointRecord",
    "WebhookReceiptRecord",
    "WorkflowDefinitionRecord",
    "WorkflowRunRecord",
    "WorkflowStepRunRecord",
    "WorkflowTransitionHistoryRecord",
    "WorkflowVersionRecord",
    "WorkflowVersionStepRecord",
]
